spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/database
  username: postgres
  password: Nandini@323
  driver-class-name: org.postgresql.Driver




#To get output of query on console    
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    format_sql: true
  
  hibernate:
    ddl-auto: update
    show-sql : true

